first version task 03
mitrofun/thinknetica-golang pull request #4
Opened 2021-05-25 06:27 UTC by mitrofun

2021-05-26 02:09 UTC, DmitriyVTitov requested changes
Конструктор не правильный, а так всё очень чисто.

2021-05-26 02:09 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +		}
чего бы вдруг fatal-то? ну недоступен сайт, подумаешь!

2021-05-26 02:09 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	scanIndex.New()
New - конструктор, а не метод. Должен возвращать объект.

2021-05-26 02:09 UTC, DmitriyVTitov commented on 03-index/pkg/crawler/spider/spider.go
> +}
вот пример конструктора - нормально написано!

2021-05-26 02:09 UTC, DmitriyVTitov commented on 03-index/pkg/index/index.go
> +}
разве я уже вас тут не поправлял?

2021-06-28 14:34 UTC, DmitriyVTitov requested changes
Замечания не учтены.

2021-06-28 14:34 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	}
ничего не поменялось: опять один сайт недоступен - и всё, Фатал!

2021-06-28 14:37 UTC, mitrofun commented on 03-index/cmd/gosearch.go
> +	}
разве log.Fatal  это не про логирование?, может для меня важно )

2021-06-28 14:46 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	}
Так почитайте комментарий к функции, там всё должно быть.
Не совсем про журналирование, так сказать!

2021-06-28 14:49 UTC, mitrofun commented on 03-index/cmd/gosearch.go
> +	}
log.Fatal вызывает системный выход os.Exit ?(не очевидно, если так) Исправил следующим коммитом.

2021-06-28 15:04 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	}
А чего гадать-то? Это стандартная библиотека, там всё написано же!

2021-06-28 23:13 UTC, DmitriyVTitov requested changes
Что-то не туда.

2021-06-28 23:13 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	}
стало ещё хуже :)
вот вы сканируете 10 сайтов и один из них не просканировался и что такого? зачем завершать работу-то?

2021-06-29 07:23 UTC, mitrofun commented on 03-index/cmd/gosearch.go
> +	}
Спасибо! до жирафа дошло!

2021-06-30 18:25 UTC, DmitriyVTitov approved these changes
Всё прилично.

2021-06-30 18:25 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +			counter = counter + 1
counter++

2021-06-30 18:25 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +		fmt.Println("Need use with flag `s` for search. For example: gosearch -s go")
flag.PrintDefault

2021-06-30 18:25 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	res := i.Search(*query)
логичнее, если бы метод индекса принимал массив документов

2021-06-30 18:25 UTC, DmitriyVTitov commented on 03-index/cmd/gosearch.go
> +	res := i.Search(*query)
я бы поиск вынес в отдельный пакет

2021-06-30 18:25 UTC, DmitriyVTitov commented on 03-index/go.mod
> +require golang.org/x/net v0.0.0-20210510120150-4163338589ed
лучше один модуль на весь репо с ДЗ

2021-06-30 18:25 UTC, DmitriyVTitov commented on 03-index/pkg/index/index.go
> +	words map[string][] int
откуда тут пробел?

2021-07-01 10:30 UTC, merged